- name: netplan apply
  command: netplan apply
  become: yes
- name: restart systemd-networkd
  service:
    name: systemd-networkd
    state: restarted
- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes
