# Authenticates with an AT&T Fiber ONT using EAP-TLS
---
- name: Install wpasupplicant
  apt:
    name: wpasupplicant
    state: latest
    install_recommends: false
- name: disable default wpa_supplicant service
  systemd:
    name: wpa_supplicant
    enabled: no
    state: stopped
    masked: yes
- name: att_eap systemd service
  template:
    src: att_eap/att_eap.service
    dest: /etc/systemd/system/att_eap.service
    owner: root
    group: root
    mode: '0644'
  notify: 
    - systemctl daemon-reload
    - restart att_eap
- name: wpa_supplicant configuration
  template:
    src: att_eap/att_eap.conf
    dest: /etc/wpa_supplicant/att_eap.conf
    owner: root
    group: root
    mode: '0640'
  notify: restart att_eap
- name: att_eap ca certificates file
  copy: 
    content: "{{ att_eap_ca_certificates_pem }}"
    dest: /etc/wpa_supplicant/att_eap_ca_certs.pem
    owner: root
    group: root
    mode: '0640'
- name: att_eap client certificate file
  copy: 
    content: "{{ att_eap_client_certificate_pem }}"
    dest: /etc/wpa_supplicant/att_eap_client_cert.pem
    owner: root
    group: root
    mode: '0640'
- name: att_eap client key file
  copy: 
    content: "{{ att_eap_client_key_pem }}"
    dest: /etc/wpa_supplicant/att_eap_client_key.pem
    owner: root
    group: root
    mode: '0640'
- name: Enable att_eap systemd service
  systemd:
    name: att_eap
    enabled: yes
    state: started
    masked: no