---
# Sets up eap_proxy, a utility for passing through authentication
# of AT&T gateways to an ONT device.
- name: Copy eap_proxy.py 
  copy:
    src: eap_proxy/eap_proxy.py
    dest: /usr/bin/eap_proxy
    owner: root
    group: root
    mode: '0754'
- name: eap_proxy.service
  template:
    src: eap_proxy/eap_proxy.service
    dest: /etc/systemd/system/eap_proxy.service
    owner: root
    group: root
    mode: '0644'
  notify: systemctl daemon-reload
- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes
- name: Template eap_proxy config
  template:
    src: eap_proxy/eap_proxy.conf
    dest: /etc/default/eap_proxy
    owner: root
    group: root
    mode: '0644'
  notify: restart eap_proxy
## EAP Network
- name: Configure eap link
  template:
    src: networkd/eap/00-eap.link
    dest: /etc/systemd/network/00-eap.link
    owner: root
    group: systemd-network
    mode: '0644'
  notify: restart systemd-networkd
- name: Configure eap network
  template:
    src: networkd/eap/10-eap.network
    dest: /etc/systemd/network/10-eap.network
    owner: root
    group: systemd-network
    mode: '0644'
  notify: restart systemd-networkd
# Enable eap proxy
- name: Enable eap_proxy.service
  ignore_errors: yes
  systemd:
    name: eap_proxy.service
    state: started
    enabled: yes
    masked: no