- name: Install mDNS Reflector
  apt:
    deb: http://http.us.debian.org/debian/pool/main/m/mdns-reflector/mdns-reflector_0.0.1+git20230914.4b4cd3b-2.1_arm64.deb
- name: Template mDNS Reflector Configuration
  template:
    src: mdns/mdns-reflector.conf
    dest: /etc/mdns-reflector/conf.d/ansible.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart mdns-reflector
- name: Enable mdns-reflector
  ignore_errors: false
  systemd:
    name: mdns-reflector
    enabled: yes
    state: started
    masked: no
