lan_address: "{{ router_ip_address | ipaddr('address') }}"
lan_network: "{{ router_ip_address | ipaddr('network') }}"
lan_netmask: "{{ router_ip_address | ipaddr('netmask') }}"
lan_broadcast: "{{ router_ip_address | ipaddr('broadcast') }}"
