---
- name: Set timezone to UTC
  timezone:
    name: UTC
- name: Enable NTP
  command: timedatectl set-ntp on
- name: Apt Cache
  apt:
    update_cache: yes
- name: Disable cloud-init network configuration
  copy:
    content: "network: {config: disabled}"
    dest: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
- name: Remove cloud-init netplan configuration
  file:
    path: /etc/netplan/50-cloud-init.yaml
    state: absent
  notify: netplan apply
- name: Let dnsmasq use any VRF with udp
  sysctl:
    name: net.ipv4.udp_l3mdev_accept
    value: '1'
    sysctl_file: /etc/sysctl.d/20-dnsmasq.conf
    reload: yes
    sysctl_set: yes
- name: Let dnsmasq use any VRF with tcp
  sysctl:
    name: net.ipv4.tcp_l3mdev_accept
    value: '1'
    sysctl_file: /etc/sysctl.d/20-dnsmasq.conf
    reload: yes
    sysctl_set: yes
- name: Create vrf0 device
  template:
    src: 00-vrf0.netdev
    dest: /etc/systemd/network/00-vrf0.netdev
    owner: root
    group: root
    mode: '0644'
  notify: restart systemd-networkd
- name: Configure vrf0 network
  template:
    src: 00-vrf0.network
    dest: /etc/systemd/network/00-vrf0.network
    owner: root
    group: root
    mode: '0644'
  notify: restart systemd-networkd
- name: Configure eth0 network
  template:
    src: 10-eth0.network
    dest: /etc/systemd/network/10-eth0.network
    owner: root
    group: root
    mode: '0644'
  notify: restart systemd-networkd
- name: Configure eth1 network
  template:
    src: 10-eth1.network
    dest: /etc/systemd/network/10-eth1.network
    owner: root
    group: root
    mode: '0644'
  notify: restart systemd-networkd
- name: Create lan_vpn VLAN network
  template:
    src: 00-eth1-2.netdev
    dest: /etc/systemd/network/00-eth1-2.netdev
    owner: root
    group: root
    mode: '0644'
  notify: restart systemd-networkd
- name: Configure lan_vpn network
  template:
    src: 20-lan_vpn.network
    dest: /etc/systemd/network/20-lan_vpn.network
    owner: root
    group: root
    mode: '0644'
  notify: restart systemd-networkd
