---
- name: Set timezone to UTC
  timezone:
    name: UTC
- name: Enable NTP
  systemd:
    name: systemd-timesyncd.service
    enabled: yes
    state: started
    masked: no
- hostname:
    name: "{{ router_hostname }}"
- name: Setup /etc/hosts
  template:
    src: hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
- name: Apt Cache
  apt:
    update_cache: yes
    cache_valid_time: 86400 # 1 day
- name: Install unattended-upgrades
  apt:
    name: unattended-upgrades
    state: latest
    install_recommends: false
- name: Apt Unused Packages
  apt:
    name:
      - snapd
      - multipath-tools
      - popularity-contest
      - byobu
      - packagekit
    state: absent
    autoclean: yes
    autoremove: yes
- name: Setup ansible-pull config
  copy:
    src: ansible-pull
    dest: /etc/default/ansible-pull
    owner: root
    group: root
    mode: '0640'
- name: Setup ansible-pull service
  copy:
    src: ansible-pull.service
    dest: /etc/systemd/system/ansible-pull.service
    owner: root
    group: root
    mode: '0644'
  notify: systemctl daemon-reload
- name: Setup ansible-pull-reconfigure service
  copy:
    src: ansible-pull-reconfigure.service
    dest: /etc/systemd/system/ansible-pull-reconfigure.service
    owner: root
    group: root
    mode: '0644'
  notify: systemctl daemon-reload
- name: Setup ansible-pull timer
  copy:
    src: ansible-pull.timer
    dest: /etc/systemd/system/ansible-pull.timer
    owner: root
    group: root
    mode: '0644'
  notify: systemctl daemon-reload
- name: Setup ansible-pull-reconfigure path watch
  copy:
    src: ansible-pull-reconfigure.path
    dest: /etc/systemd/system/ansible-pull-reconfigure.path
    owner: root
    group: root
    mode: '0644'
  notify: systemctl daemon-reload
- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes
- name: Enable ansible-pull.service
  systemd:
    name: ansible-pull.service
    enabled: yes
    masked: no
- name: Enable ansible-pull.timer
  systemd:
    name: ansible-pull.timer
    enabled: yes
    state: started
    masked: no
- name: Enable ansible-pull-reconfigure.service
  systemd:
    name: ansible-pull.service
    enabled: yes
    masked: no
- name: Enable ansible-pull-reconfigure.path
  systemd:
    name: ansible-pull-reconfigure.path
    enabled: yes
    state: started
    masked: no
- name: Disable cloud-init network configuration
  copy:
    content: "network: {config: disabled}"
    dest: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
- name: Remove cloud-init netplan configuration
  file:
    path: /etc/netplan/50-cloud-init.yaml
    state: absent
  notify: netplan apply
- name: Let dnsmasq use any VRF with udp
  sysctl:
    name: net.ipv4.udp_l3mdev_accept
    value: '1'
    sysctl_file: /etc/sysctl.d/20-dnsmasq.conf
    reload: yes
    sysctl_set: yes
- name: Let dnsmasq use any VRF with tcp
  sysctl:
    name: net.ipv4.tcp_l3mdev_accept
    value: '1'
    sysctl_file: /etc/sysctl.d/20-dnsmasq.conf
    reload: yes
    sysctl_set: yes
- name: Create vrf0 device
  template:
    src: 00-vrf0.netdev
    dest: /etc/systemd/network/00-vrf0.netdev
    owner: root
    group: root
    mode: '0644'
  notify: restart systemd-networkd
- name: Configure vrf0 network
  template:
    src: 00-vrf0.network
    dest: /etc/systemd/network/00-vrf0.network
    owner: root
    group: root
    mode: '0644'
  notify: restart systemd-networkd
- name: Configure eth0 network
  template:
    src: 10-eth0.network
    dest: /etc/systemd/network/10-eth0.network
    owner: root
    group: root
    mode: '0644'
  notify: restart systemd-networkd
- name: Configure eth1 network
  template:
    src: 10-eth1.network
    dest: /etc/systemd/network/10-eth1.network
    owner: root
    group: root
    mode: '0644'
  notify: restart systemd-networkd
- name: Create lan_vpn VLAN network
  template:
    src: 00-eth1-2.netdev
    dest: /etc/systemd/network/00-eth1-2.netdev
    owner: root
    group: root
    mode: '0644'
  notify: restart systemd-networkd
- name: Configure lan_vpn network
  template:
    src: 20-lan_vpn.network
    dest: /etc/systemd/network/20-lan_vpn.network
    owner: root
    group: root
    mode: '0644'
  notify: restart systemd-networkd
